import type { Metadata } from 'next'
import '../../styles/globals.scss'

import { Geist, Geist_Mono } from 'next/font/google'

import Footer from '@/components/Layout/Footer'
import Header from '@/components/Layout/Header'
import Main from '@/components/Layout/Main'

import { HeroUIProviders } from './HeroUIProvider'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <HeroUIProviders>
          <div className="relative flex flex-col">
            <Header />
            <Main>{children}</Main>
            <Footer />
          </div>
        </HeroUIProviders>
      </body>
    </html>
  )
}
